// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessusFormation.Data;

namespace ProcessusFormation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200717231742_nameid")]
    partial class nameid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ProcessusFormation.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Role");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("Valide");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Compétence.CompetenceEvaluationFroidModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Competence");

                    b.Property<string>("Critere10");

                    b.Property<string>("Degre");

                    b.Property<int>("IdEvaluation");

                    b.Property<int>("Niveau_acquis");

                    b.Property<int>("Niveau_actuel");

                    b.HasKey("Id");

                    b.ToTable("CompetenceEvaluationFroids");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Compétence.CompetenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Domaine");

                    b.Property<string>("Label");

                    b.Property<string>("Niveau");

                    b.HasKey("Id");

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Compétence.DomaineModel", b =>
                {
                    b.Property<int>("DomaineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomDomaine");

                    b.HasKey("DomaineId");

                    b.ToTable("Domaines");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Compétence.LabelModel", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DomaineId");

                    b.Property<int>("Niveau");

                    b.Property<string>("NomLabel");

                    b.HasKey("LabelId");

                    b.HasIndex("DomaineId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Compétence.MetierModel", b =>
                {
                    b.Property<int>("MetierId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DomaineId");

                    b.Property<int>("LabelId");

                    b.Property<int>("Niveau");

                    b.Property<string>("UserId");

                    b.HasKey("MetierId");

                    b.ToTable("Metiers");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Evaluation.EvaluationChaud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Commentaire1");

                    b.Property<string>("Commentaire2");

                    b.Property<string>("Commentaire3");

                    b.Property<DateTime>("Date_DebutFormation");

                    b.Property<DateTime>("Date_Evaluation_Chaud");

                    b.Property<DateTime>("Date_FinFormation");

                    b.Property<string>("Direction");

                    b.Property<string>("Fonction");

                    b.Property<string>("Formateur");

                    b.Property<string>("Lequelles");

                    b.Property<string>("Lieu");

                    b.Property<string>("Matricule");

                    b.Property<string>("Nom_Participant");

                    b.Property<string>("Organisme");

                    b.Property<string>("PourqouiA");

                    b.Property<string>("PourqouiB");

                    b.Property<string>("Prenom_Participant");

                    b.Property<string>("QuestionA");

                    b.Property<string>("QuestionB");

                    b.Property<string>("QuestionC");

                    b.Property<int>("Score_Evaluation");

                    b.Property<int>("Score_Satisfaction");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.ToTable("EvaluationChauds");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Evaluation.EvaluationFroid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autres1");

                    b.Property<string>("Autres2");

                    b.Property<string>("Comment");

                    b.Property<string>("Commentaire1");

                    b.Property<string>("Critere1");

                    b.Property<string>("Critere2");

                    b.Property<string>("Critere3");

                    b.Property<string>("Critere4");

                    b.Property<string>("Critere5");

                    b.Property<string>("Critere6");

                    b.Property<string>("Critere7");

                    b.Property<string>("Critere8");

                    b.Property<string>("Critere9");

                    b.Property<DateTime>("Date_Debut");

                    b.Property<DateTime>("Date_Evaluation_Froid");

                    b.Property<DateTime>("Date_Fin");

                    b.Property<string>("Direction");

                    b.Property<string>("Fonction");

                    b.Property<string>("Formateur");

                    b.Property<string>("Lesquelles");

                    b.Property<string>("Lieu");

                    b.Property<string>("Matricule");

                    b.Property<string>("Nom_Participant");

                    b.Property<string>("Organisme");

                    b.Property<string>("PourquoiA");

                    b.Property<string>("PourquoiB");

                    b.Property<string>("Prenom_Participant");

                    b.Property<string>("Sinon");

                    b.Property<string>("Theme");

                    b.Property<string>("question_A");

                    b.Property<string>("question_B");

                    b.Property<string>("question_C");

                    b.HasKey("Id");

                    b.ToTable("EvaluationFroids");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Evaluation.EvaluationFroidParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autres1");

                    b.Property<string>("Comment");

                    b.Property<string>("Commentaire1");

                    b.Property<DateTime>("Date_Debut");

                    b.Property<DateTime>("Date_Evaluation_Froid");

                    b.Property<DateTime>("Date_Fin");

                    b.Property<string>("Direction");

                    b.Property<string>("Fonction");

                    b.Property<string>("Formateur");

                    b.Property<string>("Lesquelles");

                    b.Property<string>("Lieu");

                    b.Property<string>("Matricule");

                    b.Property<string>("Nom_Participant");

                    b.Property<string>("Organisme");

                    b.Property<string>("PourquoiA");

                    b.Property<string>("PourquoiB");

                    b.Property<string>("Prenom_Participant");

                    b.Property<string>("Theme");

                    b.Property<string>("question_A");

                    b.Property<string>("question_B");

                    b.Property<string>("question_C");

                    b.HasKey("Id");

                    b.ToTable("EvaluationFroidParticipants");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Evaluation.Intermidiaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DirectActivId");

                    b.Property<int>("EvaluatFroidId");

                    b.Property<string>("ParticipantId");

                    b.HasKey("Id");

                    b.ToTable("Intermidiaires");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.BesoinCollecteModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activite")
                        .IsRequired();

                    b.Property<string>("Bareme_TFP")
                        .IsRequired();

                    b.Property<float>("Cout_Totale_previsionnel");

                    b.Property<float>("Cout_unitaire");

                    b.Property<DateTime>("Date_Debut");

                    b.Property<DateTime>("Date_Fin");

                    b.Property<string>("Duree")
                        .IsRequired();

                    b.Property<float>("Frais_de_deplacement");

                    b.Property<float>("Imputation");

                    b.Property<string>("Intitule_Formation")
                        .IsRequired();

                    b.Property<string>("Justification_du_besoin")
                        .IsRequired();

                    b.Property<float>("Montant_recuperer");

                    b.Property<int>("Nombre_de_jours");

                    b.Property<string>("Nombre_de_participants")
                        .IsRequired();

                    b.Property<string>("Organisme_de_formation")
                        .IsRequired();

                    b.Property<string>("Priorite")
                        .IsRequired();

                    b.Property<string>("nom_formateur");

                    b.Property<string>("type_de_formation")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BesoinCollectes");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.BesoinFormationModel", b =>
                {
                    b.Property<string>("BesoinFormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Activite");

                    b.Property<string>("Intitule_Formation");

                    b.Property<string>("Justification_du_besoin");

                    b.Property<string>("Nombre_de_participants");

                    b.Property<string>("Priorite");

                    b.HasKey("BesoinFormationId");

                    b.ToTable("BesoinFormationModels");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.FormateurModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom_Formateur");

                    b.Property<string>("Organisme_prestataire");

                    b.Property<string>("Period");

                    b.Property<int>("Score");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.ToTable("Formateurs");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.ParticipantFormation", b =>
                {
                    b.Property<string>("BesoinFormationId");

                    b.Property<string>("ParticipantId");

                    b.Property<string>("ParticipantModelParticipantId");

                    b.HasKey("BesoinFormationId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ParticipantModelParticipantId");

                    b.ToTable("ParticipantFormation");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.ParticipantModel", b =>
                {
                    b.Property<string>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.HasKey("ParticipantId");

                    b.ToTable("ParticipantModels");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.ParticipantToFormationModel", b =>
                {
                    b.Property<string>("IdFormation");

                    b.Property<string>("Id");

                    b.HasKey("IdFormation", "Id");

                    b.HasIndex("Id");

                    b.ToTable("ParticipantToFormations");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.SuiviFormationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activite");

                    b.Property<string>("Intitule_Formation")
                        .IsRequired();

                    b.Property<string>("Justification_du_besoin")
                        .IsRequired();

                    b.Property<string>("Nombre_Table");

                    b.Property<string>("Nombre_de_participants")
                        .IsRequired();

                    b.Property<string>("Organisme_de_formation")
                        .IsRequired();

                    b.Property<string>("Priorite")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("SuiviFormations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProcessusFormation.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProcessusFormation.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProcessusFormation.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProcessusFormation.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProcessusFormation.Models.Compétence.LabelModel", b =>
                {
                    b.HasOne("ProcessusFormation.Models.Compétence.DomaineModel", "Domaines")
                        .WithMany("Labels")
                        .HasForeignKey("DomaineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.ParticipantFormation", b =>
                {
                    b.HasOne("ProcessusFormation.Models.Formation.BesoinFormationModel", "BesoinFormationModel")
                        .WithMany("ParticipantFormations")
                        .HasForeignKey("BesoinFormationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProcessusFormation.Models.Formation.ParticipantModel", "ParticipantModel")
                        .WithMany("ParticipantFormations")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProcessusFormation.Models.Formation.ParticipantModel")
                        .WithMany("BesoinFormationModel")
                        .HasForeignKey("ParticipantModelParticipantId");
                });

            modelBuilder.Entity("ProcessusFormation.Models.Formation.ParticipantToFormationModel", b =>
                {
                    b.HasOne("ProcessusFormation.Models.ApplicationUser", "ApplicationUsers")
                        .WithMany("ParticipantToFormations")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProcessusFormation.Models.Formation.BesoinFormationModel", "BesoinFormation")
                        .WithMany("ParticipantToFormations")
                        .HasForeignKey("IdFormation")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
